[package]
name = "friday-network"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
friday-core = { path = "../friday-core" }
tokio.workspace = true
serde.workspace = true
bincode.workspace = true
thiserror.workspace = true
tracing.workspace = true
bytes.workspace = true
